//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTECAM.Presupuesto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public long Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdClavePresupuestalRemitente { get; set; }
        public Nullable<int> IdClavePresupuestalDestinataria { get; set; }
        public int IdMes { get; set; }
        public int IdTipoDeTransaccion { get; set; }
        public decimal Monto { get; set; }
        public string Motivo { get; set; }
        public bool Activo { get; set; }
    
        public virtual ClavesPresupuestales ClavesPresupuestales { get; set; }
        public virtual ClavesPresupuestales ClavesPresupuestales1 { get; set; }
        public virtual Meses Meses { get; set; }
        public virtual TiposDeTransacciones TiposDeTransacciones { get; set; }
    }
}
